#  ** This file is part of the Ordinator Project.
#  **
#  ** - Ordinator -
#  **
#  ** Copyright 2020 by SwordLord - the coding crew and the contributing authors
#  **
#  ** Travis integration to automatically compile and release binaries after commits.

language: python
python:
  - '2.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
  - platformio platform install espressif32 --with-package tool-mkspiffs
script:
  - platformio --version
  - platformio run
#  - platformio run -t buildfs